// <auto-generated />
namespace Casgem_CodeFirstProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class new_database : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new_database));
        
        string IMigrationMetadata.Id
        {
            get { return "202307130552580_new_database"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
